LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE    := libdlinput_drv

LOCAL_CFLAGS    := -DHAVE_CONFIG_H
LOCAL_C_INCLUDES := $(LOCAL_PATH) $(LOCAL_PATH)/src $(GLOBAL_X11_INCLUDES)
LOCAL_SRC_FILES := dummy-input.c
LOCAL_SHARED_LIBRARIES := libXFree86
include $(BUILD_SHARED_LIBRARY)
